name: Deploy

on:
  pull_request
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.event}}
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.PAT}}
    - name: Caching
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/terraform-plan
        key: ${{github.sha}}
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true
    - name: Init
      run: terraform init
    - name: Plan
      id: plan
      if: github.event_name == 'pull_request' && github.event.type == 'synchronize'
      run: terraform plan -out $GITHUB_WORKSPACE/terraform-plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
    
