name: Deploy

on:
  push:
    branches: [ master, mytest ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set Git credentials
      env: 
        GITHUB_PASSWORD: ${{secrets.PAT}}
      run: |
        echo password=$GITHUB_PASSWORD >> creds.txt
        echo protocol=https >> creds.txt
        echo host=github.com >> creds.txt
        echo username=helaili >> creds.txt
        echo " " >> creds.txt
        cat creds.txt
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init
    - run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
    - run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 


