name: Deploy with approval

on:
  pull_request
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.PAT}}
    - name: Caching
      uses: actions/cache@v1
      with:
        path: ~/terraform-plan
        key: ${{github.sha}}
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true
    - name: Init
      run: terraform init
    - name: Plan
      id: plan
      if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
      run: |
        mkdir ~/terraform-plan
        terraform plan -out ~/terraform-plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
    - name: Apply
      if: github.event_name == 'pull_request' && github.event.action == 'labeled'
      run: terraform apply -auto-approve ~/terraform-plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
    - run: terraform destroy -auto-approve ~/terraform-plan
      if: github.event_name == 'pull_request' && github.event.action == 'labeled'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 

    
