name: Deploy

on:
  pull_request
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.PAT}}
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true
    - name: Init
      run: terraform init
    - name: Plan
      id: plan
      run: terraform plan -out $HOME/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
    - run: echo ${{ steps.plan.outputs.stdout }}

